### PR TITLE
Add `babashka-project-tasks' command

### PR DESCRIPTION
**Pull request by olavfosse**
```
Add `babashka-project-tasks' command

This command is intended to be used with `project-switch-project', as
described in the docstring. In this context it has two advantages over
`babashka-tasks':

1. `babashka-tasks' will search for bb.edn files in
`default-directory' and `default-directory''s parent directories. This
means that when invoked by `project-switch-project' it will pick a
bb.edn file from the project of the current file you're editing,
instead of the project you're switching to.

2. When running `project-switch-project' and selecting the Babashka
task execution command, it is undesireable that the command recurses
into parent directories if there is no bb.edn file in the root
directory of the project.
```

### CODE REVIEW

**Comment by licht1stein** [comment]
Thanks for the PR! Looks like a very good addition, please add the relevant docs to the readme, including the code to add to init.el to add it to project switch menu, if you can

**Comment by olavfosse** [comment]
Thanks, will do tomorrow :^)

**Comment by olavfosse** [comment]
Done :)

**Comment by licht1stein** [comment]
Great! But a better example code block would be the one adding to the existing project actions, not replacing them completely, what do you think?

**Comment by olavfosse** [comment]
Well, it depends on whether you do it as part of configuring project.el or as part of  configuring babashka.el. Personally I do the former in my configuration. Since both options are equally valid, why not document both instead of repeating one in two places? In any case it doesn't really matter. This feels like bikeshedding at this point so I think it's best if you just change it however you prefer :-)

**Comment by licht1stein** [comment]
Thanks for the PR!

**Comment by olavfosse** [comment]
Thanks for the package :^)

**Pull request merged**
